### ISSUE TITLE
Release 0.13.0

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/build-tools#110]
We need a new release to use the latest version of schemas check tool in the spec repo before spec release 0.13.0.

There is no release guidelines in this repo, so I am not sure how to make a release. @open-telemetry/specs-approvers who can help with this and/or write a paragraph in CONTRIBUTING.md to explain how to make the release?

**Comment by codeboten** [comment]
@arminru pinging you as you seem to have created the last 4 releases 😬

**Comment by arminru** [comment]
There you go: https://github.com/open-telemetry/build-tools/releases/tag/v0.13.0
https://hub.docker.com/r/otel/build-tool-schemas/tags
