### ISSUE TITLE
Make diffs in table regeneration issues more visible

### ISSUE THREAD

**Issue by hughesjj** [open-telemetry/build-tools#120]
I (and apparently another engineer) had trouble seeing why exactly the build process was failing, the error message only being 

```
File {blah} contains a table that would be reformatted.
```

I've since found the tool is very particular about whitespace and even the number of dashes in a table header.

**Comment by Oberon00** [comment]
For anybody seeing this: You are not meant to try to correct this by hand-editing yourself. The tool is not built as a linter, but as a generator. The tool checks for byte-by-byte equality for what it generates.
