### ISSUE TITLE
Semconv generated code causes doxygen warnings

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/build-tools#126]
Using `opentelemetry-specifications` version `1.16.0`.

In particular, the spec for `browser.platform` contains, in the note:

```
          Note that some (but not all) of these values can overlap with values
          in the [`os.type` and `os.name` attributes](./os.md).
```

Using `build-tools` version `0.14.0`

Using `opentelemetry-cpp` version `1.8.1`, with the following generation script:

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/buildscripts/semantic-convention/generate.sh

After generation, the C++ code for `browser.platform` looks like:

```
/**
 * The platform on which the browser is running
 *
 * <p>Notes:
  <ul> <li>This value is intended to be taken from the <a
href="https://wicg.github.io/ua-client-hints/#interface">UA client hints API</a> ({@code
navigator.userAgentData.platform}). If unavailable, the legacy {@code navigator.platform} API SHOULD
NOT be used instead and this attribute SHOULD be left unset in order for the values to be
consistent. The list of possible values is defined in the <a
href="https://wicg.github.io/ua-client-hints/#sec-ch-ua-platform">W3C User-Agent Client Hints
specification</a>. Note that some (but not all) of these values can overlap with values in the <a
href="./os.md">{@code os.type} and {@code os.name} attributes</a>. However, for consistency, the
values in the {@code browser.platform} attribute should capture the exact value that the user agent
provides.</li> </ul>
 */
static constexpr const char *kBrowserPlatform = "browser.platform";
```

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/include/opentelemetry/sdk/resource/semantic_conventions.h#L38-L53

Note in particular how the original link to `os.md` is encoded:

```
Note that some (but not all) of these values can overlap with values in the <a
href="./os.md">{@code os.type} and {@code os.name} attributes</a>.
```

Using `doxygen` version `1.9.5`, it reports the following warnings:

```
/.../semantic_conventions.h:49: warning: Illegal command @iliteral found as part of a <a>..</a> block
/.../semantic_conventions.h:49: warning: Illegal command @endiliteral found as part of a <a>..</a> block
/.../semantic_conventions.h:49: warning: Illegal command @iliteral found as part of a <a>..</a> block
/.../semantic_conventions.h:49: warning: Illegal command @endiliteral found as part of a <a>..</a> block
```

There are a few similar warnings for other semantic conventions.

Doxygen complains about the `{@code os.type}` and `{@code os.name}` seen inside an `<a>anchor</a>`

The expected result is to have a complete chain that generates clean doxygen documentation, without warnings.

About the point of failure, not sure where the root cause actually is:

- Is the syntax  used (see below) considered valid in the spec ?
- Does the generator produces the correct output for this syntax ?
- Does the template code used in opentelemetry-cpp needs changes to fix this, and how ?
- Should doxygen accepts `@code` inside an `<a></a>` tag ?

```
Spec syntax:
[`os.type` and `os.name` attributes](./os.md) 
```

Please clarify and provide guidance here, in particular on which part (spec, generator, generator template) should be fixed, with suggestions if known.

If this turns out to be a doxygen limitation, what is the best way to implement a work around ?

Thanks.

**Comment by Oberon00** [comment]
> Is the syntax used (see below) considered valid in the spec?

Yes, this is valid markdown. inline-code markup can be nested in links.

> Does the generator produces the correct output for this syntax?

This depends on your template.

> Does the template code used in opentelemetry-cpp needs changes to fix this, and how ?

Most likely. It is possible that you need to add a helper function for this. Although, don't newer versions of Doxygen also work directly with doxygen?

**Comment by marcalff** [comment]
Thanks @Oberon00

> > Is the syntax used (see below) considered valid in the spec?
> 
> Yes, this is valid markdown. inline-code markup can be nested in links.
> 

Ok, thanks for confirming.

> > Does the generator produces the correct output for this syntax?
> 
> This depends on your template.

Ok, so it depends only on the template.
My concern was to clarify if the template is given correct data to process, which seems ok then.

> 
> > Does the template code used in opentelemetry-cpp needs changes to fix this, and how ?
> 
> Most likely. It is possible that you need to add a helper function for this.

Will try to figure this out then.

> Although, don't newer versions of Doxygen also work directly with markdown?

Currently doxygen comments for semantic conventions are generated in the C++ header file produced (this is for opentelemetry-cpp), so it is not written in markdown.

**Comment by marcalff** [comment]
Closing the issue then, since the point of failure is downstream from build-tools.

**Comment by Oberon00** [comment]
I think markdown might also be supported in the header comments: https://doxygen.nl/manual/docblocks.html#docstructure
