### ISSUE TITLE
Markdown generator should use LF line endings on Windows too

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/build-tools#16]
Currently the markdown generator (probably others too) uses the platform line endings, which are CRLF on Windows. It should be changed to use LF, always.

This can be controlled with the `newline='\n'` option to open: https://docs.python.org/3/library/functions.html#open

It would probably make sense to use a wrapper function for open() that specifies both the utf-8 encoding and the LF line endings.

**Comment by jsuereth** [comment]
We've been moving markdown/codegen generation to weaver.   Closing this as wontfix, can reopen against weaver if this is an issue.
