### ISSUE TITLE
Add note for metrics yaml definitions

### ISSUE THREAD

**Issue by trask** [open-telemetry/build-tools#167]
This isn't a blocker, as we can add the note manually to the markdown file for now, but it would be nice to add the note in the yaml definition.

Related to https://github.com/open-telemetry/opentelemetry-specification/issues/3418 and https://github.com/open-telemetry/opentelemetry-specification/pull/3352#issuecomment-1517987640

**Comment by Oberon00** [comment]
I think this is #15. The note/brief for the group is currently missing everywhere in the markdown output, except for the attributes themselves.
