### ISSUE TITLE
Allow sharing/inheriting notes/brief from overriden ref attributes

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/build-tools#183]
It seems it's not possible to share brief/notes (might also be others?) from an attribute that is a ref and overrides the "original" attribute. 

For example, the case with the `server.address` attribute:

1. Originally defined in `server.yaml` with its own brief/note field
2. Referenced in `http-common.yaml` from `server.yaml`, overriding the brief/note
3. Referenced in `traces/http` from `http-common.yaml` -> Doesn't get the note from `http-common.yaml`

This makes it so we need to copy/paste things over and over. See [this PR](https://github.com/open-telemetry/semantic-conventions/pull/109#discussion_r1229944545) for the problem in action.

It would be great if we could also "share" the notes/brief from an attribute that has been overridden somehow.

**Comment by Oberon00** [comment]
One suggestion of how a solution could look like: Reference the overriden attribute using `group_id:attribute_name` (new colon-syntax to distinguish normal fully.qualified.attribute_name syntax), where group_id is the ID of the referencing group (NB: Not the prefix!).

**Comment by lmolkova** [comment]
I think this is fixed in #204, and here's semconv changes https://github.com/open-telemetry/semantic-conventions/pull/367.

So closing this one, feel free to reopen if I missed something.
