### ISSUE TITLE
Improve documentation of code generator

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/build-tools#198]
There are a couple of [issues](https://github.com/open-telemetry/build-tools/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Adocumentation) about our current [code generator documentation](https://github.com/open-telemetry/build-tools/tree/main/semantic-conventions#code-generator). In general, I feel the process to get the things working is not clear. There are several arguments that are not documented at all, and folks need either to ask here, or dig into the code themselves to find things out. 

I can tell from my own experience as a "first timer". It was particularly painful for me when I was trying to get it to work for the .NET SDK https://github.com/open-telemetry/opentelemetry-dotnet/pull/2069. 

I feel we need to cover in the docs:

- All the parameters the tool accepts and what they do
- Examples of how to use it to generate code files from YAML
  - Here we could either link to the existing one we know in Java + another language as JS

**Comment by ezinneanne** [comment]
Hello, can I work on this?

**Comment by joaopgrassi** [comment]
Hi @ezinneanne sure! Feel free to work on it and reach out if something is unclear.

**Comment by joaopgrassi** [comment]
@ezinneanne are you working on this? Let me know so I can assign it to you then. Thank you!

**Comment by ezinneanne** [comment]
Hello, I would love to work on this but am preoccupied at the moment. You can assign it to someone else. Thank you @joaopgrassi

**Comment by lmolkova** [comment]
I think this was covered in #243 and will be fully merged in #295

**Comment by lmolkova** [comment]
There were a lot of docs improvements in the 0.24.0 release - https://github.com/open-telemetry/build-tools/blob/v0.24.0/semantic-conventions/README.md#code-generator

I think we can still improve it further documenting remaining filters and tests, so I'm keeping it open.

**Comment by AnushkaShreyam** [comment]
Hi, Can I work on documenting the 0.24.0 release? Let me know...

**Comment by lmolkova** [comment]
closing this issue - we're sunsetting otel/semconvgen in favor of [weaver](https://github.com/open-telemetry/weaver) https://github.com/open-telemetry/build-tools/issues/322 and won't make any improvements here.
