### ISSUE TITLE
Add readme and repository url to DockerHub

### ISSUE THREAD

**Issue by legendecas** [open-telemetry/build-tools#224]
The DockerHub image page https://hub.docker.com/r/otel/semconvgen is lacking necessary information and makes it hard to trace back to the document of the image.

It would be better to have a readme page on the DockerHub and link back to this repository.

**Comment by joaopgrassi** [comment]
@arminru do you know how/whom can help us with this?

**Comment by arminru** [comment]
@tigrannajaryan can you look into this, please?

**Comment by tigrannajaryan** [comment]
AFAIK none of the otel org's images have this info. Is there a way to supply this information as part of publishing an image? We want to decentralize this, we cannot ask Docker hub Admin (typically me) to maintain this information for 24 (and growing) different images.

**Comment by legendecas** [comment]
It seems like there is no docker built-in support to upload a readme. But https://github.com/christian-korneck/docker-pushrm provides a way to upload readme to DockerHub, by cli or GitHub Actions. (I didn't verify it)

**Comment by lmolkova** [comment]
closing this issue - we're sunsetting otel/semconvgen in favor of [weaver](https://github.com/open-telemetry/weaver) https://github.com/open-telemetry/build-tools/issues/322 and won't make any improvements here.
