### ISSUE TITLE
Give Maintain permissions to specs-semconv-maintainers so they can merge PRs and publish releases

### ISSUE THREAD

**Issue by arminru** [open-telemetry/build-tools#233]
I'd like to give Maintain permissions to @open-telemetry/specs-semconv-maintainers so they can merge PRs in this repo and publish new releases of the semconv tool.

For the other sub-projects (schemas + protobuf tooling + cpp_format_tools) we have @open-telemetry/specs-approvers as code owners as per https://github.com/open-telemetry/build-tools/blob/main/.github/CODEOWNERS.
This way, the semconv maintainers would only be able to merge PRs in `semantic-conventions/` after approving them and technically also other PRs already approved by @open-telemetry/specs-approvers, but it's clear enough that this is out of scope for the semconv group, so it shouldn't be an issue IMHO.

**Comment by arminru** [comment]
@open-telemetry/technical-committee would you be fine with handing out these merge permissions?

In the past, I've always been the only one merging those semconv PRs and while I was out of office the others were blocked, which is not ideal.

**Comment by tigrannajaryan** [comment]
Sounds good to me.

**Comment by arminru** [comment]
Alright, sounds like there are no objections.
I'll give Maintain permissions to @open-telemetry/specs-semconv-maintainers then.
In https://github.com/open-telemetry/build-tools/issues/232 we'll also add a maintainer list to make this more transparent.

cc @open-telemetry/technical-committee
