### ISSUE TITLE
Consider using proper type annotations

### ISSUE THREAD

**Issue by arminru** [open-telemetry/build-tools#234]
I think the "proper" solution would be to switch from legacy `# type:` comments to using actual annotations.

For example, instead of:

```python
mandatory_keys = ("id", "brief")  # type: Tuple[str, ...]
```

use:

```python
mandatory_keys: Tuple[str, ...] = ("id", "brief")
```

And since we probably rely on 3.9+ anyway, one could even use the built-in `tuple` support for generic arguments and drop the `import`, using:

```python
mandatory_keys: tuple[str, ...] = ("id", "brief")
```

Not a blocking comment, just a suggestion.

_Originally posted by @Oberon00 in https://github.com/open-telemetry/build-tools/pull/231#discussion_r1379690037_

**Comment by lmolkova** [comment]
Given that we're sunsetting build-tools (https://github.com/open-telemetry/build-tools/issues/322) and it's not applicable to weaver, I'm going to close it
