### ISSUE TITLE
Add the semconvgen Library to PyPi (semantic-conventions package)

### ISSUE THREAD

**Issue by Kevin-Ngo** [open-telemetry/build-tools#253]
- There are some cases where using the SemanticConvention model outside of a CLI would be useful
- Third-party scripts that perform validation on Semantics on top of the standard syntax validation found in the semconvgen models
- Adding the package to PyPi makes it easily available for other applications/services to reference it as a dependency

**Comment by Oberon00** [comment]
Are we really sure we need this? We have enough compatibility problems and under-documentation with what Jinja templates can access. If we expose this, even more changes will be breaking changes.

At the moment, the issue claims that there are "some cases" where it would be useful. Please list some concrete use cases.

**Comment by Kevin-Ngo** [comment]
The cases that I can think of, and one that I want to use, is wanting access to the syntax validation that is present in the `SemanticConvention` model for the sake of making my own code generation script based off semantic conventions. I don't really need to use the CLI, so having access to the model via a library would make it so that users can use the model (SemanticConvention) and its out of the box syntax validation on the YAML files.

**Comment by lmolkova** [comment]
closing this issue - we're sunsetting otel/semconvgen in favor of [weaver](https://github.com/open-telemetry/weaver) https://github.com/open-telemetry/build-tools/issues/322 and won't make any improvements here.
