### ISSUE TITLE
Add `stability` property to semconv.schema.json

### ISSUE THREAD

**Issue by arminru** [open-telemetry/build-tools#276]
It seems like we forgot to define the `stability` property in the semconv schema (used for IDE hints):
https://github.com/open-telemetry/build-tools/blob/ca02f82a2af66901f01028c0d2a28e871cc2b5e4/semantic-conventions/semconv.schema.json

_Originally posted by @arminru in https://github.com/open-telemetry/build-tools/pull/272#discussion_r1504112524_

**Comment by lmolkova** [comment]
Good catch!

I'm adding it here https://github.com/open-telemetry/build-tools/pull/267/files#diff-7d02e6243524a7a259272ddbf2875a2875a5308b2e751de28be28b76725c0296, but can definitely extract into a separate PR

**Comment by lmolkova** [comment]
Fixed in #267
