### ISSUE TITLE
update python docker image to 3.10 or greater

### ISSUE THREAD

**Issue by hughesjj** [open-telemetry/build-tools#284]
Currently we're using `python3.9` in the [`Dockerfile`](https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/Dockerfile#L1)

However, `python3.9` [does not support type unions](https://docs.python.org/3.9/library/stdtypes.html#types-union), yet [we use such](https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/src/opentelemetry/semconv/templating/markdown/__init__.py#L531).  This functionality from [PEP 604](https://peps.python.org/pep-0604/) was not introduced [until `python3.10`](https://docs.python.org/3.10/library/stdtypes.html#types-union)

Updating the [`Dockerfile`](https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/Dockerfile#L1) to [`3.10-alpine`](https://github.com/docker-library/python/blob/1576b93b13ae6fe75c30ce75583da0c3541f0cb2/3.10/alpine3.19/Dockerfile) would resolve this issue, but I note that in [`setup.cfg`](https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/setup.cfg#L34) we specify `python_requires>=3.6` and list notes up to `python3.9`.  We should also update this to at least `python3.10`.

**Comment by lmolkova** [comment]
I believe it was fixed in #285 and #286. Thank you!
