### ISSUE TITLE
Support for "map" conventions based on prefixes

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/build-tools#29]
See this suggested semantic convention for HTTP headers: open-telemetry/opentelemetry-specification#1061.

Right now, I think it is not possible to specify this in the semantic convention generator. It would be useful however to generate a constant for the `http.request.header` prefix (or `http.request.header.` with a trailing dot, or a function `string httpRequestHeaderName(string key) { return 'http.request.header' + key; }`.

In the markdown, this should probably be designated by adding `.*` to the name of the attribute. E.g. like this:

| Attribute  | Type | Description  | Examples  | Required |
|---|---|---|---|---|
| `http.request.header.<key>` | string[] | HTTP request headers, `<key>` being the HTTP Header name (case preserving), the value being the header values. | `http.request.header.Content-Type`=`["application/json"]`; `http.request.X-Forwarded-for`=`["1.2.3.4", "1.2.3.5"]` | No |

In the YAML source:

* The type could be specified like `type: prefix_map: string[]`.
* Examples need to be handled specially here, as they need to include both the key (suffix) and a value.

**Comment by Oberon00** [comment]
Caveat: We should not implement this before discussing over in the spec repo if that prefix-based scheme is something we may want to use more often.

**Comment by lmolkova** [comment]
I believe it's fixed in the https://github.com/open-telemetry/build-tools/pull/186
