### ISSUE TITLE
Add stability/deprecation to events (log_events)

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/build-tools#292]
We don't render stability/deprecation status of events. 

As events/log_events work continues, it would be great if we could require stability on events and supported deprecating them.
We should be able to see the status in the markdown.

Update: we should also add events to compatibility check and prevent them from being deleted.

**Comment by MSNev** [comment]
Agree, its probably also related to #259

**Comment by jsuereth** [comment]
Closing in lieu of @lmolkova work on rendering events using weaver in semconv.
