### ISSUE TITLE
Host stability badges within otel ecosystem

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/build-tools#298]
From https://github.com/open-telemetry/build-tools/pull/278#discussion_r1506157403

shields.io is designed to provide badges for things like GitHub pipeline status, it's cached by the browser, by the GH and on the shields.io content distribution side.

But it's an external dependency, which might go down or degrade, we might hit rate-limits affecting anyone browsing semconvs.

As an immediate mitigation we can disable badge generation in favor of plain text, but in the long term we should consider hosting badges ourselves:
- on opentelemetry.io
- inside semconv repo
- ...

**Comment by arminru** [comment]
cc @open-telemetry/docs-maintainers

**Comment by cartermp** [comment]
I'm not inherently opposed to hosting on the otel.io site, although I think it's more likely that we'd go down than sheilds.io would.

**Comment by svrnm** [comment]
Are the rate limits the major concern, are we hitting them on a regular basis? Based on the initial comment this is not for build pipelines etc, but for more or less static badges:

```
        return "![Stable](https://img.shields.io/badge/-stable-lightgreen)"
```

Our website is hosted on netlify, shields.io on cloudflare, so both should be fairly stable. Hosting it ourselves might add some extra control over caching I guess.

**Comment by lmolkova** [comment]
we're going to have them added to almost every attribute in semconv repo and on otel.io. They are static (and there 3 distinct ones).
Interestingly enough GitHub already caches them plus they are cached by user browser. So in practice I don't expect any rate-limiting problems. If we ever do, we can turn them off - they are not essential. We can also reconsider our approach then.

otel.io (there are multiple badges on the page, but only each badge is requested only once, also cached in memory):
<img width="1817" alt="image" src="https://github.com/open-telemetry/build-tools/assets/2347409/95c60012-e7f2-4f0a-ace4-4a6d9df4442a">


semconv repo (same here)
<img width="1868" alt="image" src="https://github.com/open-telemetry/build-tools/assets/2347409/3088d043-365f-4552-a3f2-69c6324c9af1">

**Comment by svrnm** [comment]
yes, looks like caching is solving most of the concerns. And, as long as you keep an alternate title for each badge I don't see any issues even if whatever service is used is down.
