### ISSUE TITLE
Review unused/low-used yaml features

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/build-tools#303]
- [x] constraints (see #293)
- [x] UnitSemanticConvention (#309)
- [x] MetricGroupSemanticConvention  (#309)
- [x] ScopeSemanticConvention (#309)
- [ ] ResourceSemanticConvention

**Comment by jsuereth** [comment]
Resource semconv is out of scope for now, as we have a short moratorium for the entities SiG to make progress before refactoring.
