### ISSUE TITLE
Support shared enum definitions

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/build-tools#32]
I noticed that we have duplicated the list of well-known cloud providers to both the `cloud.provider` resource attribute and the `faas.invoked_provider` attribute.

With this we keep approaching [XSD](https://en.wikipedia.org/wiki/XML_Schema_(W3C)) 😄

**Comment by lmolkova** [comment]
Related: https://github.com/open-telemetry/semantic-conventions/issues/799

With reusing attributes across signals, we can now merge attributes that have the same list of members into one (such as `cloud.provder`)

**Comment by jsuereth** [comment]
We've started merging attributes in many places now, so this issue is more limited.   Closing as won't fix, but will reopen if it becomes a larger issue again.
