### ISSUE TITLE
any_of markdown output is misleading if each set only has one member

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/build-tools#33]
E.g. see https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/semantic_conventions/database.md#connection-level-attributes

> **Additional attribute requirements:** At least one of the following sets of attributes is required:
>
> * `net.peer.name`
> * `net.peer.ip`

Obviously the set here is `{"net.peer.name", "net.peer.ip"}`, so you need both. Except: This is wrong! There are two sets, one contains only `net.peer.name` and the other only `net.peer.ip`.

I think if each set contains only one member, the text above the list MUST change to "At least one of the following ~~sets of~~ attributes is required:" (without the ~~sets of~~).

**Comment by thisthat** [comment]
I am not a native speaker, so I cannot judge properly which is the best phrase to use here. 
Would you also remove "sets of" in the case where multiple attributes are listed? 
An example of this is in the [HTTP Client](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/semantic_conventions/http.md#http-client) semantic convention:
> **Additional attribute requirements:** At least one of the following sets of attributes is required:
>
> * `http.url`
> * `http.scheme`, `http.host`, `http.target`
> * `http.scheme`, [`net.peer.name`](span-general.md), [`net.peer.port`](span-general.md), `http.target`
> * `http.scheme`, [`net.peer.ip`](span-general.md), [`net.peer.port`](span-general.md), `http.target`

**Comment by Oberon00** [comment]
I think if at least one set has more than one member, the current phrasing is clear and in these cases I would keep it as-is.

**Comment by lmolkova** [comment]
see #293

**Comment by lmolkova** [comment]
Closing this since we no longer support `constraints` - 310
