### ISSUE TITLE
Code generator readme is outdated

### ISSUE THREAD

**Issue by arminru** [open-telemetry/build-tools#34]
The code generator readme (https://github.com/open-telemetry/build-tools/tree/main/semantic-conventions#code-generator) is outdated and contains a couple of broken links. The generation steps in opentelemetry-java were changed and the generated constants moved.

The new locations are:
https://github.com/open-telemetry/opentelemetry-java/tree/main/buildscripts/semantic-convention
https://github.com/open-telemetry/opentelemetry-java/tree/main/semconv

**Comment by kennykguo** [comment]
Please assign this issue to me

**Comment by Oberon00** [comment]
@kennykguo I assigned you the issue.

**Comment by marcalff** [comment]
> The new locations are: https://github.com/open-telemetry/opentelemetry-java/tree/main/buildscripts/semantic-convention https://github.com/open-telemetry/opentelemetry-java/tree/main/semconv

These do not seem to exist either.
