### ISSUE TITLE
ValidationError: Semantic Convention faas_span.http includes http.server but the latter cannot be found

### ISSUE THREAD

**Issue by lonewolf3739** [open-telemetry/build-tools#38]
I am running into this issue when trying to use `otel/semconvgen` to generate semantic convention code. How do I resolve this?

**Comment by thisthat** [comment]
Hi @lonewolf3739! Could you please share the whole command that you are using to invoke `otel/semconvgen`? 
Do you pass the whole [trace](https://github.com/open-telemetry/opentelemetry-specification/tree/main/semantic_conventions/trace) folder to the tool?

**Comment by lonewolf3739** [comment]
@thisthat Here is the command I was using. There is same problem with trace/resource folder.

```sh
docker run --rm \
  -v ${SCRIPT_DIR}/opentelemetry-specification/semantic_conventions/resource:/source \
  -v ${SCRIPT_DIR}/templates:/templates \
  -v ${ROOT_DIR}/opentelemetry-sdk/src/opentelemetry/sdk/resources/:/output \
  otel/semconvgen \
  -f /source code \
  --template /templates/semantic_attributes.j2 \
  --output /output/attributes.py \
```

**Comment by lonewolf3739** [comment]
To add more context; I was using the spec v1.1.0.

**Comment by thisthat** [comment]
@lonewolf3739 thank you for the command :) 
I noticed that you are using the image without pinning the version. Maybe you have locally an old version which is not compatible with the spec yaml v1.1.0.
Could you please try again using version `0.2.1`? 
```
docker run --rm \
  -v ${SCRIPT_DIR}/opentelemetry-specification/semantic_conventions/resource:/source \
  -v ${SCRIPT_DIR}/templates:/templates \
  -v ${ROOT_DIR}/opentelemetry-sdk/src/opentelemetry/sdk/resources/:/output \
  otel/semconvgen:0.2.1 \
  -f /source code \
  --template /templates/semantic_attributes.j2 \
  --output /output/attributes.py
```

**Comment by lonewolf3739** [comment]
Pinning to `0.2.1` worked. I am going to close this issue then.
