### ISSUE TITLE
Support clarifying shared attributes in other files

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/build-tools#41]
Currently, the way to refer to another attribute while clarifying its usage in a downstream semantic convention file, for example how aws-sdk does here

https://github.com/open-telemetry/opentelemetry-specification/blob/412fb5774cefc32ff9b7f47ef80e9e7d245e1e2e/semantic_conventions/trace/instrumentation/aws-sdk.yml#L13

The code generator seems to not correctly use the base definition. Perhaps this was too hacky of a way to do this approach but I think we need a way to refer to convventions from other files, and without breaking generation.

Also see:
https://github.com/open-telemetry/opentelemetry-specification/discussions/1607

/cc @weyert

**Comment by weyert** [comment]
For an example see this generated file that uses `0.3.1` of the generator against the `HEAD` of `specification`-repo:
https://github.com/open-telemetry/opentelemetry-js/blob/3302972f519f936a800adb1bf9a26a71cb5c9ed5/packages/opentelemetry-semantic-conventions/src/trace/SemanticAttribute.ts#L469

**Comment by Oberon00** [comment]
Can you provide a link to your template? If you just do something like `all attributes | unique by full name`, you will get a random definition of each attribute if it was ref'd. But you should be able to filter for the primary definition somehow in the Jinja template. As this seems to be a trap that is easy to fall into, I think we should improve the generator tool though, e.g. by providing a list that only contains primary definitions out of the box.

**Comment by Oberon00** [comment]
> Perhaps this was too hacky of a way to do this 

No, you used it exactly as designed. This is why `ref` allows overriding `brief`, etc.

**Comment by weyert** [comment]
@Oberon00 Interesting I didn't know that. The template file can be found here: https://github.com/open-telemetry/opentelemetry-js/blob/9b889efff306715adb6136b9e84539da3d20be0a/scripts/semconv/templates/SemanticAttributes.ts.j2

**Comment by Oberon00** [comment]
This is the property you probably need to filter on https://github.com/open-telemetry/build-tools/blob/v0.3.1/semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py#L82-L84 using https://jinja.palletsprojects.com/en/2.11.x/templates/#selectattr.

**Comment by Oberon00** [comment]
Actually by using `is_local`, the `unique` should no longer be needed.

**Comment by weyert** [comment]
Thank you, I will give this a try and report back

**Comment by weyert** [comment]
Looks ike I was able to make it work with:

```
  {%- for attribute in attributes if attribute.is_local and not attribute.ref %}
```
