### ISSUE TITLE
Semantic  convention generator adds more than one blank line, failing mdlint

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/build-tools#47]
See https://github.com/open-telemetry/opentelemetry-specification/pull/1759#issuecomment-861645499

The PR in question has two enums in a single convention, and the first one has a note on one of the members. As a result, two consecutive newlines are printed between the footnote and the next enum table.

**Comment by bryce-b** [comment]
I can take this ticket, but I don't think i'll be able to get a PR in until next week

**Comment by Oberon00** [comment]
Just comment on the ticket if/when you start working on it.

**Comment by bryce-b** [comment]
I'm working on it now, but I'm doing a half day today and I'm OOF tomorrow.
