### ISSUE TITLE
to_const_name generates invalid variable identifiers

### ISSUE THREAD

**Issue by legendecas** [open-telemetry/build-tools#59]
Recently in semantic conventions, two new types of id were introduced:

- Alibaba Cloud (https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/resource/cloud.yaml#L11)
- 1xRTT (https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/general.yaml#L94)

The const names generated for those ids are `ALIBABA CLOUD` and `1XRTT` respectively. Those generated values are not valid variable identifiers in most languages.

In opentelemetry-js, we use `to_const_name` to generate keys for those ids: https://github.com/open-telemetry/opentelemetry-js/blob/main/scripts/semconv/templates/SemanticAttributes.ts.j2#L57. In this case, the keys should be valid variable identifiers.

Should we change the semantic conventions or update the generator to generate valid identifiers?

**Comment by Oberon00** [comment]
I think we don't have any spaces in the semantic conventions so far, so my preferred solution would be to change alibaba cloud to use an underscore, like all other comparable names.

I would prefer the same for 1xRTT. There is a reason we have separate "value" and "id" fields in the YAML.

**Comment by Oberon00** [comment]
I'm working on this..
