### ISSUE TITLE
Allow at least some form of templating also for markdown

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/build-tools#71]
The code generator uses a flexible mechanism based on Jinja2 to generate output. Yet the markdown output is generated with hard-coded Python code.
Consider introducing more flexibility into markdown generation with Jinja. Ideally, completely replace the Python code for markdown with Jinja templates which allow good structuring and are quite powerful. Just the replacement mechanism (finding the HTML comments) will best stay in Pyhton.

From https://github.com/open-telemetry/build-tools/pull/70#issuecomment-926407468

**Comment by lmolkova** [comment]
I believe it's fixed with weaver - see https://github.com/open-telemetry/semantic-conventions/tree/main/templates/registry/markdown
