### ISSUE TITLE
SemConv MD generator should write "or" between examples

### ISSUE THREAD

**Issue by thisthat** [open-telemetry/build-tools#8]
From https://github.com/open-telemetry/opentelemetry-specification/pull/928#discussion_r485198089

Having an example per row makes it harder to understand that they are multiple examples and not a single one. The MD generator should use "or" instead of "<br>" to separate examples.

**Comment by Oberon00** [comment]
I would prefer quoting strings and adding commas, which is more similar to how semantic conventions do it today AFAIK.

See https://github.com/open-telemetry/opentelemetry-specification/pull/925#discussion_r484439234
