### ISSUE TITLE
Establish a build-tools SIG

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/build-tools#90]
I think this project has enough contributions to be its own SIG that has approvers and maintainers. We should consider some of the instrumentation SIG members for the semantic convention tools as well as people that made contributions @arminru, @Oberon00, @atoulme, @lmolkova, myself for the proto docker.

@open-telemetry/technical-committee @open-telemetry/specs-approvers @open-telemetry/instr-wg thoughts on this?

**Comment by yurishkuro** [comment]
+1, even though people do not need to ask for permission to form a SIG. The fact that this repo exists, with its own contributors & maintainers, means SIG already de-facto exists.

**Comment by tigrannajaryan** [comment]
Yes, and we should also encourage to have more maintainers for this repo.

Add me as codeowner for `schemas` directory.

**Comment by jamesmoessis** [comment]
👋  As someone from the instrumentation WG I'm happy to put my hand up for the semantic conventions area.

**Comment by lmolkova** [comment]
We have semconv tooling group now

Semantic Conventions: Tooling | Wednesday at 07:00 PT | [Google Doc](https://docs.google.com/document/d/1ygwXgOFRF01UfUOgMr_ElyL7fSDPchTKSrqfj-_HeyA) | [#otel-semantic-conventions-wg](https://cloud-native.slack.com/archives/C041APFBYQP) | [calendar-semconv](https://groups.google.com/a/opentelemetry.io/g/calendar-semconv) |

Come join us!
