### ISSUE TITLE
[semconvgen] Feature Request: Add option to disable attribute id regex validation

### ISSUE THREAD

**Issue by wperron** [open-telemetry/build-tools#91]
Hey folks 👋  We have existing code that emits attributes with IDs that do not match the semconv regex (for example, some of them are pascal case). We want to use the semconvgen tool with a custom template, but ideally we would like to be able to disable the regex validation on the attribute IDs as an option flag for semconvgen. In our case, relabelling would be too long/costly as we have a _huge_ codebase in multiple languages to comb through.

**Comment by lmolkova** [comment]
We no longer use build-tools for semantic conventions  and new tool - [weaver](https://github.com/open-telemetry/weaver) does not have strict limitations.

We enforce format via [policies](https://github.com/open-telemetry/semantic-conventions/blob/main/policies/yaml_schema.rego) in otel-semconv repos that don't by default apply to external conventions.

So, I'm going to close this issue. If there is something we can do in [weaver](https://github.com/open-telemetry/weaver), please open the new issue there.
